name: Check & deploy to DockerHub

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:

jobs:
  perform-check:
    uses: ./.github/workflows/test_lint.yml
  docker:
    runs-on: ubuntu-latest
    environment: DockerHub
    needs:
      - perform-check
    strategy:
      matrix:
        configurations:
          - dockerfile: "Dockerfile"
            tags: |
              edgeneko/neko-image-gallery:latest
              edgeneko/neko-image-gallery:latest-cuda
              edgeneko/neko-image-gallery:latest-cuda12.1
            args: |
              CUDA_VERSION=12.1
          - dockerfile: "Dockerfile"
            tags: edgeneko/neko-image-gallery:latest-cuda11.8
            args: |
              CUDA_VERSION=11.8
          - dockerfile: "cpu-only.Dockerfile"
            tags: edgeneko/neko-image-gallery:latest-cpu
            args: ""
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          file: ${{ matrix.configurations.dockerfile }}
          push: true
          tags: ${{ matrix.configurations.tags }}
          build-args: ${{ matrix.configurations.args }}
